<?php

$formData = $this->view->dados;

echo "
<html lang=\"pt-BR\">
     <div class='container mt-2'> 
     
	 <h1 class='text-center'>Editar Pessoa</h1>
     <h3 class='mt-4'>Dados Pessoais</h3>
     
    <form action='' method='Post'>
      <div class='form-group'>
        <label for='nome'>Nome Completo</label>
        <input 
        required 
        type='text' 
        class='form-control' 
        id='nome' 
        name='nome' 
        value='" . $formData['nome_completo'] . "'
        placeholder='Nome completo'>
      </div>
      
      <div class='form-group'>
        <label for='telefone'>Telefone</label>
        <input 
        required 
        type='text' 
        class='form-control' 
        id='telefone' 
        name='telefone'
        value='" . $formData['telefone'] . "'
        placeholder='(99) 99999-9999'>
      </div>
      
      <div class='form-group'>
        <label for='cpf'>CPF</label>
        <input 
        required 
        type='text' 
        class='form-control' 
        id='cpf' 
        name='cpf'
        maxlength='11'
        value='" . $formData['cpf'] . "'
        placeholder='000.000.000-00'>
      </div>
      
        <div class='form-group'>
        <label for='dataNascimento'>Data de Nascimento</label>
        <input 
        type='date' 
        class='form-control' 
        id='dataNascimento' 
        name='dataNascimento'
        value='" . date("Y-m-d", strtotime($formData['data_nascimento'])) . "'
        placeholder='dd/mm/aaaa'>
      </div>
         
     <h3 class='mt-4'>Dados Endereço</h3>
        
      <div class='form-group mt-4'>
        <label for='cep'>CEP</label>
        <input 
        required
        type='text' 
        class='form-control' 
        id='cep' 
        name='cep'
        value='" . $formData['cep'] . "' 
        placeholder='CEP'> 
      </div>
      
      <div class='form-group'>
        <label for='logradouro'>Logradouro</label>
        <input 
        required 
        type='text' 
        class='form-control' 
        id='logradouro' 
        name='logradouro'
        value='" . $formData['logadouro'] . "'  
        placeholder='Logradouro'>
      </div>
      
       <div class='form-group'>
        <label for='localidade'>Localidade</label>
        <input 
        required 
        type='text' 
        class='form-control' 
        id='localidade' 
        value='" . $formData['localidade'] . "'   
        name='localidade'
        placeholder='Localidade'>
      </div>
        
      <div class='form-group'>
        <label for='bairro'>Bairro</label>
        <input 
        required 
        type='text' 
        class='form-control' 
        id='bairro' 
        name='bairro'
        value='" . $formData['bairro'] . "'    
        placeholder='Bairro'>
      </div>
      
      <div class='form-group'>
        <label for='uf'>UF</label>
        <input 
        required 
        type='text' 
        class='form-control' 
        id='uf' 
        name='uf'
        value='" . $formData['uf'] . "'     
        placeholder='UF'>
      </div>      
      
      <div class='form-group'>
        <label for='complementoEndereco'>Complemento</label>
        <input 
        required 
        type='text' 
        class='form-control' 
        id='complementoEndereco' 
        name='complementoEndereco'
        value='" . $formData['complemento'] . "'     
        placeholder='Complemento'>
      </div>
      
        <button type='submit' class='btn btn-primary mt-4'>Atualizar</button>  
        <button type='button' class='btn btn-warning mt-4' onclick=\"location.href='/'\">Voltar</button>
        
    </form> 
      </div>
    </html>
    ";
?>